logging:
  level:
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

server:
  servlet:
    context-path: /acoes-ods/v1/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/acoes_db
    username: postgres
    password: admin.123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  api-docs:
    path: "/api-docs"
