app:
  admin:
    username: willcq
    password: admin.123
    roles:
      - ADMIN

logging:
  level:
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.security]": DEBUG

server:
  servlet:
    context-path: /acoes-ods/v1/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/acoes_db
    username: postgres
    password: admin.123

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  jackson:
    date-format: dd/MM/yyyy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  api-docs:
    path: "/api-docs"
