app:
  swagger:
    title: "SCPODS API"
    description: "Backend do Sistema para Cadastro de Projetos relacionados aos Objetivos de Desenvolvimento Sustentável na Universidade Federal do Espírito Santo."
    version: 1.0

    author:
      name: "Willian Conceição Queiroz"
      email: "willian.cqueiroz@gmail.com"
      url: "https://github.com/WillCQ97"

    license:
      name: "MIT License"
      url: https://github.com/WillCQ97/scpods-backend/blob/main/LICENSE

server:
  servlet:
    context-path: /acoes-ods/v1/

spring:
  jackson:
    date-format: dd/MM/yyyy

  profiles:
    active:
    - dev

springdoc:
  api-docs:
    path: "/api-docs"
