app:
  admin:
    username: admin
    password: admin.123
    roles:
      - ADMIN

  swagger:
    title: "SCPODS API"
    description: "Backend do Sistema para Cadastro de Projetos relacionados aos Objetivos de Desenvolvimento Sustentável na Universidade Federal do Espírito Santo."
    version: 1.0

    author:
      name: "Willian Conceição Queiroz"
      email: "willian.cqueiroz@gmail.com"
      url: "https://github.com/WillCQ97"

    license:
      name: "MIT License"
      url: https://github.com/WillCQ97/scpods-backend/blob/main/LICENSE

logging:
  level:
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.security]": DEBUG

server:
  servlet:
    context-path: /acoes-ods/v1/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVER_NAME:localhost}:${POSTGRESQL_SERVER_PORT:5432}/${POSTGRESQL_DATABASE_NAME:acoes_db}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:admin.123}

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  jackson:
    date-format: dd/MM/yyyy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  api-docs:
    path: "/api-docs"
