version: '3.1'

services:

  db:
    container_name: postgis_ods
    image: postgis/postgis
    restart: always
    
    environment:
      POSTGRES_PASSWORD: admin.123
    
    ports:
      - 5432:5432

    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
